# GitHub Actions workflow for automatic deployment
name: Deploy Streamlit App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test imports
      run: |
        python -c "from src.utils import logger"
        python -c "from src.data_preprocessing import DataPreprocessor"
        python -c "from src.feature_engineering import FeatureEngineer"
        python -c "from src.model_training import ModelTrainer"
    
    - name: Test Streamlit app
      run: |
        python -c "from webapp.app import load_dataset; print('App imports successful')"

  deploy-to-heroku:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "your-salary-prediction-app"
        heroku_email: "your-email@example.com"
